# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
# paginate: 5
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://rhitabrat.github.io/
baseurl: /
title: Rhitabrat Pokharel
author: Rhitabrat Pokharel
description: Personal blog and resume
avatar: profile.png
email: pokharelrhitabrat@gmail.com
github: Rhitabrat # username
twitter: Rhitabrat
linkedin: rhitabrat
stackoverflow: users/8736603/rhitik-pokharel   #e.g: users/2735833/proton1h1
googlescholar : citations?user=YbmOhHUAAAAJ&hl=en
facebook: Rhitabrat

website: rhitabrat.github.io
website_full: https://rhitabrat.github.io/
tel: +977 9849811681
tel_full: tel:+9779849811681
google_maps: 'https://goo.gl/maps/tVPEq9MHW8jczmTV9'
address:
  street: Balaju
  postcode: 44600
  city: Kathmandu
  country: Nepal
#Comment out if you don't want disqus
# disqus: username
# google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]

sass:
    sass_dir: _sass

# Defining plugins here is necessary because certain hosts (e.g. Github Pages, Netlify) do not build sites using Bundler.
plugins:
  - jekyll-paginate
  - jekyll-menus
